name: Update and Deploy on EC2
on:
  push:
    branches:
      - master
jobs:
  deploy-on-ec2:
    name: SSH and Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUB_IP_PROD }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd envision-benefits-marketing/

            sudo docker-compose down
            
            git checkout master

            # git pull latest changes
            git pull origin master

            # Rebuild and run everything
            sudo docker-compose up -d --build

            # Run migrations and init data
            make init

            # Remove unused images
            sudo docker system prune --force